const NOTIF_FETCH_REQUEST = 'NOTIF_FETCH_REQUEST';
const NOTIF_FETCH_RESPONSE = 'NOTIF_FETCH_RESPONSE';
const NOTIF_FETCH_ERROR = 'NOTIF_FETCH_ERROR';

export { NOTIF_FETCH_REQUEST, NOTIF_FETCH_RESPONSE, NOTIF_FETCH_ERROR };
