const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

const NOTIF_ENABLE_LOADER = 'NOTIF_ENABLE_LOADER';
const NOTIF_DISABLE_LOADER = 'NOTIF_DISABLE_LOADER';

export {
  LOGIN_ENABLE_LOADER,
  LOGIN_DISABLE_LOADER,
  NOTIF_ENABLE_LOADER,
  NOTIF_DISABLE_LOADER,
};
