const LOGIN_REQUEST = 'LOGIN_REQUEST';
const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
const LOGIN_FAILED = 'LOGIN_FAILED';
const LOG_OUT = 'LOG_OUT';

export { LOGIN_REQUEST, LOGIN_RESPONSE, LOGIN_FAILED, LOG_OUT };
